const fs = require('fs');
const fp = 'd:/Codebuddy_space/信佰监理服务管理系统/src/pages/changeControl/requestPage.tsx';
let c = fs.readFileSync(fp, 'utf8').replace(/\r\n/g, '\n');

// Fix: when status is already '一审通过', nextLevel should be 2
c = c.replace(
  "  const handleReviewSubmit = (payload: { status: '通过' | '驳回'; comment: string; reviewer: string }) => {\n    if (!currentItem) return\n    const key = currentItem.key\n    const existingRecords = approvalMap[key] || []\n    const nextLevel = (existingRecords.length + 1)\n\n    const newRecord: ApprovalRecord = {\n      key: `${key}-r${nextLevel}-${Date.now()}`,\n      code: `${currentItem.code}-R${nextLevel}`,\n      level: nextLevel,\n      reviewer: payload.reviewer,\n      comment: payload.comment,\n      status: payload.status,\n      date: dayjs().format('YYYY-MM-DD HH:mm:ss'),\n    }\n    setApprovalMap(prev => ({ ...prev, [key]: [...existingRecords, newRecord] }))\n\n    if (payload.status === '驳回') {\n      setList(prev => { const r = prev.map(item => item.key === key ? { ...item, status: '待审批' as CRStatus } : item); return r })\n      message.success('已驳回，返回待审批')\n    } else {\n      const newStatus: CRStatus = currentItem.status === '待审批' ? '一审通过' : '已审批'\n      setList(prev => { const r = prev.map(item => item.key === key ? { ...item, status: newStatus, currentLevel: nextLevel } : item); return r })\n      message.success(newStatus === '已审批' ? '终审已通过' : '一审通过，等待总监理工程师终审')\n    }\n    setIsReviewModalVisible(false)\n    setCurrentItem(null)\n  }",
  "  const handleReviewSubmit = (payload: { status: '通过' | '驳回'; comment: string; reviewer: string }) => {\n    if (!currentItem) return\n    const key = currentItem.key\n    const existingRecords = approvalMap[key] || []\n    const nextLevel = currentItem.status === '一审通过' ? 2 : (existingRecords.length + 1)\n\n    const newRecord: ApprovalRecord = {\n      key: `${key}-r${nextLevel}-${Date.now()}`,\n      code: `${currentItem.code}-R${nextLevel}`,\n      level: nextLevel,\n      reviewer: payload.reviewer,\n      comment: payload.comment,\n      status: payload.status,\n      date: dayjs().format('YYYY-MM-DD HH:mm:ss'),\n    }\n    setApprovalMap(prev => ({ ...prev, [key]: [...existingRecords, newRecord] }))\n\n    if (payload.status === '驳回') {\n      setList(prev => { const r = prev.map(item => item.key === key ? { ...item, status: '待审批' as CRStatus } : item); return r })\n      message.success('已驳回，返回待审批')\n    } else {\n      const newStatus: CRStatus = currentItem.status === '待审批' ? '一审通过' : '已审批'\n      setList(prev => { const r = prev.map(item => item.key === key ? { ...item, status: newStatus, currentLevel: nextLevel } : item); return r })\n      message.success(newStatus === '已审批' ? '终审已通过' : '一审通过，等待总监理工程师终审')\n    }\n    setIsReviewModalVisible(false)\n    setCurrentItem(null)\n  }"
);

fs.writeFileSync(fp, c.replace(/\n/g, '\r\n'), 'utf8');
console.log('fixed');
